# Generated by Django 6.1.1 on 2026-10-06 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales_app', '0001_initial'),
        ('users_app', '0001_initial'),
        ('workshop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id_config', models.AutoField(help_text='Identificador único de la configuración.', primary_key=True, serialize=False)),
                ('clave', models.TextField(blank=True, help_text='Clave de búsqueda para el parámetro.', null=True)),
                ('ultima_modif', models.DateTimeField(blank=True, help_text='Sello de tiempo de la última modificación.', null=True)),
                ('descripcion', models.CharField(help_text='Descripción del parámetro de configuración.', max_length=100)),
                ('valor', models.CharField(blank=True, help_text='Valor asignado al parámetro.', max_length=10, null=True)),
            ],
            options={
                'db_table': 'configuracion_sistema',
            },
        ),
        migrations.CreateModel(
            name='CopiaSeguridad',
            fields=[
                ('id_backup', models.AutoField(help_text='Identificador único del respaldo generado.', primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(help_text='Fecha de creación del respaldo.')),
                ('automatico', models.BooleanField(help_text='Indica si el respaldo fue generado automáticamente.')),
                ('ubicacion_archivo', models.CharField(help_text='Ruta o ubicación del archivo del respaldo.', max_length=500)),
                ('version', models.CharField(help_text='Versión del sistema al momento del respaldo.', max_length=50)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', help_text='Identificador único del usuario.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_app.usuario')),
            ],
            options={
                'db_table': 'copia_seguridad',
            },
        ),
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id_log', models.AutoField(help_text='Identificador único del evento de log.', primary_key=True, serialize=False)),
                ('fecha_hora', models.TimeField(help_text='Sello de tiempo exacto del evento.')),
                ('accion', models.CharField(help_text='Descripción de la acción registrada.', max_length=255)),
                ('detalle', models.CharField(blank=True, help_text='Información adicional del evento si corresponde.', max_length=1000, null=True)),
                ('tipo', models.CharField(help_text='Tipo de log generado.', max_length=50)),
                ('modulo_origen', models.CharField(help_text='Módulo del sistema donde se originó el evento.', max_length=50)),
                ('tabla_afectada', models.CharField(blank=True, help_text='Nombre de la tabla afectada por el evento.', max_length=150, null=True)),
                ('id_registro_afectado', models.CharField(blank=True, help_text='Identificador del registro afectado dentro de la tabla.', max_length=150, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', help_text='Identificador único del usuario.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_app.usuario')),
            ],
            options={
                'db_table': 'log_sistema',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(help_text='Identificador único de la notificación.', primary_key=True, serialize=False)),
                ('mensaje', models.CharField(help_text='Contenido del mensaje enviado al usuario.', max_length=1000)),
                ('tipo', models.CharField(help_text='Categoría o tipo de la notificación.', max_length=100)),
                ('fecha_envio', models.DateField(help_text='Fecha en la que se emitió la notificación.')),
                ('leida', models.BooleanField(help_text='Indica si la notificación fue leída por el usuario.')),
                ('id_beneficio', models.ForeignKey(blank=True, db_column='id_beneficio', help_text='Identificador único del beneficio asociado.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_app.beneficio')),
                ('id_dispositivo', models.ForeignKey(blank=True, db_column='id_dispositivo', help_text='Identificador único del dispositivo.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_app.dispositivo')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', help_text='Identificador único del usuario.', on_delete=django.db.models.deletion.CASCADE, to='users_app.usuario')),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
    ]
