# Generated by Django 6.1.1 on 2026-10-06 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog_app', '0001_initial'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id_mediopago', models.AutoField(help_text='Identificador único del medio de pago.', primary_key=True, serialize=False)),
                ('estado', models.BooleanField(help_text='Estado del medio de pago (activo/inactivo).')),
                ('nombre_medio_pago', models.CharField(help_text='Nombre del medio de pago.', max_length=100)),
                ('recargo', models.DecimalField(decimal_places=2, help_text='Porcentaje o monto de recargo del medio de pago.', max_digits=10)),
            ],
            options={
                'db_table': 'medio_pago',
            },
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id_beneficio', models.AutoField(help_text='Identificador único del beneficio o sugerencia.', primary_key=True, serialize=False)),
                ('motivo', models.CharField(help_text='Motivo que originó la recomendación.', max_length=500)),
                ('fecha', models.DateField(help_text='Fecha en que se generó la sugerencia.')),
                ('enviado_momento_compra', models.BooleanField(help_text='Indica si se envió en el momento de la compra.')),
                ('enviado_durante_carrito', models.BooleanField(help_text='Indica si se generó mientras el cliente armaba el carrito.')),
                ('por_desc', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de descuento asociado a la sugerencia.', max_digits=10, null=True)),
                ('tiempo_disp', models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo de vigencia del beneficio medido en horas.', max_digits=10, null=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', help_text='Identificador único del producto.', on_delete=django.db.models.deletion.CASCADE, to='catalog_app.producto')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', help_text='Identificador único del usuario.', on_delete=django.db.models.deletion.CASCADE, to='users_app.usuario')),
            ],
            options={
                'db_table': 'beneficio',
            },
        ),
        migrations.CreateModel(
            name='CarritoCompra',
            fields=[
                ('id_carrito', models.AutoField(help_text='Identificador único del carrito de compras.', primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(help_text='Fecha en que se creó el carrito.')),
                ('estado', models.CharField(help_text='Estado del carrito (activo, finalizado o abandonado).', max_length=50)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', help_text='Identificador único del usuario.', on_delete=django.db.models.deletion.CASCADE, to='users_app.usuario')),
            ],
            options={
                'db_table': 'carrito_compra',
            },
        ),
        migrations.CreateModel(
            name='CarritoProducto',
            fields=[
                ('id_carrito_producto', models.AutoField(help_text='Identificador único del detalle de carrito.', primary_key=True, serialize=False)),
                ('id_carrito', models.ForeignKey(db_column='id_carrito', help_text='Identificador del carrito de compra.', on_delete=django.db.models.deletion.CASCADE, to='sales_app.carritocompra')),
                ('id_producto', models.ForeignKey(db_column='id_producto', help_text='Identificador del producto en el carrito.', on_delete=django.db.models.deletion.RESTRICT, to='catalog_app.producto')),
            ],
            options={
                'db_table': 'carrito_producto',
            },
        ),
        migrations.AddField(
            model_name='carritocompra',
            name='productos',
            field=models.ManyToManyField(help_text='Relación M:N entre carritos y productos.', through='sales_app.CarritoProducto', to='catalog_app.producto'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(help_text='Identificador único de la venta.', primary_key=True, serialize=False)),
                ('metodo_entrega', models.CharField(help_text='Método de entrega de la venta.', max_length=100)),
                ('fecha_venta', models.DateField(help_text='Fecha en que se realizó la venta.')),
                ('estado_venta', models.CharField(help_text='Estado actual de la venta.', max_length=50)),
                ('codigo_sec', models.CharField(blank=True, help_text='Código de seguridad para ventas virtuales.', max_length=100, null=True)),
                ('monto_subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal de productos más costos de reparaciones asociadas.', max_digits=10)),
                ('costo_envio', models.DecimalField(decimal_places=2, help_text='Costo total de envío aplicado a la venta.', max_digits=10)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', help_text='Identificador único del usuario.', on_delete=django.db.models.deletion.RESTRICT, to='users_app.usuario')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(help_text='Identificador único del pago.', primary_key=True, serialize=False)),
                ('monto_pagado', models.DecimalField(decimal_places=2, help_text='Importe abonado en el pago.', max_digits=10)),
                ('fecha_pago', models.DateField(help_text='Fecha en que se realizó el pago.')),
                ('detalle', models.CharField(blank=True, help_text='Descripción general u observaciones del pago.', max_length=500, null=True)),
                ('cod_operacion', models.CharField(blank=True, help_text='Código de operación cuando aplica transferencia.', max_length=100, null=True)),
                ('ruta_comprobante', models.CharField(blank=True, help_text='Ruta o URL del comprobante generado.', max_length=500, null=True)),
                ('medio_pago', models.ForeignKey(db_column='id_mediopago', help_text='Medio de pago utilizado.', on_delete=django.db.models.deletion.RESTRICT, to='sales_app.mediopago')),
                ('id_venta', models.ForeignKey(db_column='id_venta', help_text='Identificador único de la venta.', on_delete=django.db.models.deletion.CASCADE, to='sales_app.venta')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle', models.AutoField(help_text='Identificador único del renglón de detalle de venta.', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(help_text='Unidades del producto adquiridas en el renglón.')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario congelado al momento de la compra.', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Monto total de este renglón (cantidad por precio).', max_digits=10)),
                ('id_producto', models.ForeignKey(db_column='id_producto', help_text='Identificador único del producto.', on_delete=django.db.models.deletion.RESTRICT, to='catalog_app.producto')),
                ('id_venta', models.ForeignKey(db_column='id_venta', help_text='Identificador único de la venta.', on_delete=django.db.models.deletion.CASCADE, to='sales_app.venta')),
            ],
            options={
                'db_table': 'detalle_venta',
            },
        ),
    ]
