# Generated by Django 6.1.1 on 2026-10-06 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog_app', '0001_initial'),
        ('sales_app', '0001_initial'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaReparacion',
            fields=[
                ('id_categoria', models.AutoField(help_text='Identificador único de la categoría de reparación.', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre de la categoría de reparación.', max_length=150)),
                ('estado_activo', models.BooleanField(help_text='Indica si la categoría de reparación está activa.')),
            ],
            options={
                'db_table': 'categoria_reparacion',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id_dispositivo', models.AutoField(help_text='Identificador único del dispositivo.', primary_key=True, serialize=False)),
                ('numero_serie', models.CharField(blank=True, help_text='Número de serie o IMEI del dispositivo.', max_length=100, null=True)),
                ('fecha_registro', models.DateField(help_text='Fecha en que el dispositivo fue registrado.')),
                ('imagen', models.CharField(blank=True, help_text='URL a una imagen del dispositivo.', max_length=500, null=True)),
                ('id_modelo', models.ForeignKey(db_column='id_modelo', help_text='Identificador único del modelo.', on_delete=django.db.models.deletion.RESTRICT, to='catalog_app.modelodispositivo')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', help_text='Identificador único del usuario.', on_delete=django.db.models.deletion.RESTRICT, to='users_app.usuario')),
            ],
            options={
                'db_table': 'dispositivo',
            },
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id_reparacion', models.AutoField(help_text='Identificador único de la reparación.', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del diagnóstico o reparación.')),
                ('hora_recepcion', models.TimeField(blank=True, help_text='Sello de tiempo de recepción para el proceso.', null=True)),
                ('fecha_entrega', models.DateField(blank=True, help_text='Fecha en que el cliente retiró el dispositivo.', null=True)),
                ('etapa', models.CharField(help_text='Etapa actual del proceso de reparación.', max_length=50)),
                ('codigo_sec', models.CharField(blank=True, help_text='Código de seguridad vinculado a la reparación.', max_length=100, null=True)),
                ('desc_cliente', models.CharField(blank=True, help_text='Descripción de problemas informada por el cliente.', max_length=1000, null=True)),
                ('credencial_acceso', models.CharField(blank=True, help_text='Credenciales necesarias para probar el dispositivo.', max_length=255, null=True)),
                ('categorias', models.ManyToManyField(db_table='reparacion_categoria', help_text='Relación M:N entre reparaciones y categorías de reparación.', to='workshop_app.categoriareparacion')),
                ('id_dispositivo', models.ForeignKey(db_column='id_dispositivo', help_text='Identificador único del dispositivo.', on_delete=django.db.models.deletion.RESTRICT, to='workshop_app.dispositivo')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', help_text='Identificador único del usuario.', on_delete=django.db.models.deletion.RESTRICT, to='users_app.usuario')),
                ('id_venta', models.ForeignKey(blank=True, db_column='id_venta', help_text='Identificador único de la venta.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_app.venta')),
            ],
            options={
                'db_table': 'reparacion',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id_diagnostico', models.AutoField(help_text='Identificador único del diagnóstico técnico.', primary_key=True, serialize=False)),
                ('descripcion_falla', models.CharField(help_text='Detalle de las fallas detectadas.', max_length=1000)),
                ('fecha_diagnostico', models.DateField(help_text='Fecha en que se realizó el diagnóstico.')),
                ('costo_diagnostico', models.DecimalField(blank=True, decimal_places=2, help_text='Costo estimado del diagnóstico o reparación.', max_digits=10, null=True)),
                ('id_reparacion', models.ForeignKey(db_column='id_reparacion', help_text='Identificador único de la reparación.', on_delete=django.db.models.deletion.CASCADE, to='workshop_app.reparacion')),
            ],
            options={
                'db_table': 'diagnostico',
            },
        ),
        migrations.CreateModel(
            name='DetalleInsumoReparacion',
            fields=[
                ('id_detalle_insumo', models.AutoField(help_text='Identificador único del detalle de insumos usados en reparación.', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(help_text='Unidades instaladas o consumidas.')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio del producto congelado al asignarlo a la reparación.', max_digits=10)),
                ('id_producto', models.ForeignKey(db_column='id_producto', help_text='Identificador único del producto.', on_delete=django.db.models.deletion.RESTRICT, to='catalog_app.producto')),
                ('id_reparacion', models.ForeignKey(db_column='id_reparacion', help_text='Identificador único de la reparación.', on_delete=django.db.models.deletion.CASCADE, to='workshop_app.reparacion')),
            ],
            options={
                'db_table': 'detalle_insumo_reparacion',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(help_text='Identificador único de la calificación de reparación.', primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField(help_text='Puntuación numérica entre 1 y 5.')),
                ('comentario', models.CharField(blank=True, help_text='Opinión textual del cliente.', max_length=1000, null=True)),
                ('fecha', models.DateField(help_text='Fecha de emisión de la calificación.')),
                ('id_reparacion', models.ForeignKey(db_column='id_reparacion', help_text='Identificador único de la reparación.', on_delete=django.db.models.deletion.CASCADE, to='workshop_app.reparacion')),
            ],
            options={
                'db_table': 'calificacion',
            },
        ),
        migrations.CreateModel(
            name='BitacoraReparacion',
            fields=[
                ('id_bitacora', models.AutoField(help_text='Identificador único del evento en la bitácora.', primary_key=True, serialize=False)),
                ('fecha_hora', models.TimeField(help_text='Fecha y hora exacta del cambio registrado.')),
                ('estado_alcanzado', models.IntegerField(help_text='Nuevo estado asignado al dispositivo.')),
                ('comentario', models.CharField(help_text='Justificación técnica del cambio.', max_length=1000)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', help_text='Identificador único del usuario.', on_delete=django.db.models.deletion.RESTRICT, to='users_app.usuario')),
                ('id_reparacion', models.ForeignKey(db_column='id_reparacion', help_text='Identificador único de la reparación.', on_delete=django.db.models.deletion.CASCADE, to='workshop_app.reparacion')),
            ],
            options={
                'db_table': 'bitacora_reparacion',
            },
        ),
    ]
