# Generated by Django 6.1.1 on 2026-10-06 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog_app', '0001_initial'),
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(help_text='Identificador único del registro de stock.', primary_key=True, serialize=False)),
                ('stock_minimo', models.IntegerField(help_text='Umbral mínimo para alertas de stock bajo.')),
                ('id_producto', models.ForeignKey(db_column='id_producto', help_text='Identificador único del producto.', on_delete=django.db.models.deletion.RESTRICT, to='catalog_app.producto')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id_movimiento', models.AutoField(help_text='Identificador único del movimiento de stock.', primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(help_text='Tipo de operación realizada sobre el stock.', max_length=50)),
                ('cantidad', models.IntegerField(help_text='Número de unidades ingresadas o retiradas.')),
                ('fecha', models.DateField(help_text='Fecha del registro del movimiento.')),
                ('motivo', models.CharField(blank=True, help_text='Razón u observación del movimiento.', max_length=500, null=True)),
                ('uso_taller', models.BooleanField(help_text='Indica si el producto fue destinado al taller.')),
                ('id_venta', models.ForeignKey(blank=True, db_column='id_venta', help_text='Identificador único de la venta.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_app.venta')),
                ('id_stock', models.ForeignKey(db_column='id_stock', help_text='Identificador único del registro de stock.', on_delete=django.db.models.deletion.RESTRICT, to='inventory_app.stock')),
            ],
            options={
                'db_table': 'movimiento_stock',
            },
        ),
    ]
