# Generated by Django 6.1.1 on 2026-09-28 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria', models.AutoField(help_text='Identificador único de la categoría de producto.', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre de la categoría de producto.', max_length=150)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción de los tipos de productos incluidos.', max_length=500, null=True)),
                ('estado', models.BooleanField(help_text='Indica si la categoría está activa para nuevos productos.')),
            ],
            options={
                'db_table': 'categoria_producto',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(help_text='Identificador único de la marca.', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre comercial del fabricante.', max_length=150)),
                ('estado_activo', models.BooleanField(help_text='Indica si la marca está activa.')),
            ],
            options={
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('id_tipo_dispositivo', models.AutoField(help_text='Identificador único del tipo de dispositivo.', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del tipo de dispositivo.', max_length=100)),
                ('estado_activo', models.BooleanField(help_text='Indica si el tipo se encuentra activo.')),
            ],
            options={
                'db_table': 'tipo_dispositivo',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(help_text='Identificador único del producto.', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre comercial del producto.', max_length=255)),
                ('descripcion', models.CharField(blank=True, help_text='Detalle o especificación técnica del producto.', max_length=1000, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Precio de venta vigente para el producto.', max_digits=10)),
                ('estado', models.BooleanField(help_text='Indica el estado de disponibilidad del producto.')),
                ('apto_venta', models.BooleanField(help_text='Habilita la visibilidad del producto en el catálogo y ventas.')),
                ('apto_reparacion', models.BooleanField(help_text='Habilita consumo interno del producto para reparaciones.')),
                ('apto_consumible', models.BooleanField(help_text='Permite baja por consumo interno del producto.')),
                ('modulo_automatico', models.BooleanField(help_text='Habilita órdenes de compra automáticas para reabastecer.')),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', help_text='Identificador único de la categoría de producto.', on_delete=django.db.models.deletion.RESTRICT, to='catalog_app.categoriaproducto')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='ModeloDispositivo',
            fields=[
                ('id_modelo', models.AutoField(help_text='Identificador único del modelo.', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Denominación comercial del modelo.', max_length=150)),
                ('estado_activo', models.BooleanField(help_text='Indica si el modelo está activo.')),
                ('id_marca', models.ForeignKey(db_column='id_marca', help_text='Identificador único de la marca.', on_delete=django.db.models.deletion.RESTRICT, to='catalog_app.marca')),
                ('id_tipo_dispositivo', models.ForeignKey(db_column='id_tipo_dispositivo', help_text='Identificador único del tipo de dispositivo.', on_delete=django.db.models.deletion.RESTRICT, to='catalog_app.tipodispositivo')),
            ],
            options={
                'db_table': 'modelo',
            },
        ),
    ]
