# Generated by Django 6.1.1 on 2026-09-28 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(help_text='Identificador único de la ciudad.', primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(help_text='Nombre oficial de la ciudad.', max_length=150)),
                ('cobertura_habilitada', models.BooleanField(help_text='Indica si la ciudad tiene cobertura de envíos.')),
            ],
            options={
                'db_table': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(help_text='Identificador único del país.', primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(help_text='Nombre del país.', max_length=150)),
                ('cobertura_habilitada', models.BooleanField(help_text='Indica si el país tiene cobertura de envíos.')),
            ],
            options={
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(help_text='Identificador único de la dirección.', primary_key=True, serialize=False)),
                ('alias', models.CharField(blank=True, help_text='Nombre de referencia para la dirección.', max_length=100, null=True)),
                ('nro_calle', models.CharField(help_text='Número y nombre de la calle.', max_length=255)),
                ('nombre_barrio', models.CharField(blank=True, help_text='Barrio de la dirección.', max_length=150, null=True)),
                ('nro_dpto', models.CharField(blank=True, help_text='Número o identificación del departamento.', max_length=50, null=True)),
                ('piso', models.IntegerField(blank=True, help_text='Número de piso del domicilio.', null=True)),
                ('id_ciudad', models.ForeignKey(db_column='id_ciudad', help_text='Identificador único de la ciudad.', on_delete=django.db.models.deletion.RESTRICT, to='geo_app.ciudad')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', help_text='Identificador único del usuario.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_app.usuario')),
            ],
            options={
                'db_table': 'direccion',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(help_text='Identificador único de la provincia.', primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(help_text='Nombre oficial de la provincia.', max_length=150)),
                ('cobertura_habilitada', models.BooleanField(help_text='Indica si la provincia tiene cobertura de envíos.')),
                ('id_pais', models.ForeignKey(db_column='id_pais', help_text='Identificador único del país.', on_delete=django.db.models.deletion.RESTRICT, to='geo_app.pais')),
            ],
            options={
                'db_table': 'provincia',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='id_provincia',
            field=models.ForeignKey(db_column='id_provincia', help_text='Identificador único de la provincia.', on_delete=django.db.models.deletion.RESTRICT, to='geo_app.provincia'),
        ),
    ]
