# Generated by Django 6.1.1 on 2026-10-06 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog_app', '0001_initial'),
        ('geo_app', '0001_initial'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id_cotizacion', models.AutoField(help_text='Identificador único de la cotización.', primary_key=True, serialize=False)),
                ('tiempo_promesa', models.IntegerField(help_text='Días prometidos para la entrega.')),
                ('archivo_adjunto', models.CharField(blank=True, help_text='Ruta o URL del presupuesto formal.', max_length=500, null=True)),
                ('estado_cotizacion', models.IntegerField(help_text='Estado de la cotización en su evaluación.')),
                ('comentarios', models.CharField(blank=True, help_text='Comentarios o justificación en caso de rechazo.', max_length=1000, null=True)),
                ('fecha_validez', models.DateField(help_text='Fecha de vencimiento de precios cotizados.')),
            ],
            options={
                'db_table': 'cotizacion',
            },
        ),
        migrations.CreateModel(
            name='InvitacionCotizar',
            fields=[
                ('id_invitacion', models.AutoField(help_text='Identificador único de la invitación a cotizar.', primary_key=True, serialize=False)),
                ('token_acceso', models.CharField(blank=True, help_text='Código de acceso generado para el enlace seguro.', max_length=200, null=True)),
                ('estado_invitacion', models.IntegerField(help_text='Situación actual de la invitación a cotizar.')),
            ],
            options={
                'db_table': 'invitacion_cotizar',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_orden', models.AutoField(help_text='Identificador único de la orden de compra.', primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(help_text='Fecha en que se generó la orden de compra.')),
                ('estado_orden', models.IntegerField(help_text='Estado de la orden de compra.')),
                ('sol_tec', models.BooleanField(help_text='Indica si fue solicitada por un técnico.')),
                ('nro_remito', models.CharField(blank=True, help_text='Número de remito recibido en la entrega.', max_length=100, null=True)),
                ('tipo_entrega', models.IntegerField(help_text='Modalidad de entrega de la orden de compra.')),
                ('fecha_recepcion', models.DateField(blank=True, help_text='Fecha en que se recepcionó la orden.', null=True)),
            ],
            options={
                'db_table': 'orden_compra',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id_solicitud', models.AutoField(help_text='Identificador único de la solicitud de cotización.', primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(help_text='Fecha en que se emitió la solicitud.')),
                ('estado_solicitud', models.IntegerField(help_text='Estado actual de la solicitud según su ciclo.')),
            ],
            options={
                'db_table': 'solicitud_cotizacion',
            },
        ),
        migrations.CreateModel(
            name='CotizacionProducto',
            fields=[
                ('id_cotizacion_producto', models.AutoField(help_text='Identificador único del ítem de cotización.', primary_key=True, serialize=False)),
                ('precio_ofrecido', models.DecimalField(decimal_places=2, help_text='Precio ofrecido por el proveedor para el producto.', max_digits=10)),
                ('id_cotizacion', models.ForeignKey(db_column='id_cotizacion', help_text='Identificador único de la cotización.', on_delete=django.db.models.deletion.CASCADE, to='purchases_app.cotizacion')),
                ('id_producto', models.ForeignKey(db_column='id_producto', help_text='Identificador único del producto.', on_delete=django.db.models.deletion.RESTRICT, to='catalog_app.producto')),
            ],
            options={
                'db_table': 'cotizacion_producto',
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='id_invitacion',
            field=models.ForeignKey(db_column='id_invitacion', help_text='Identificador único de la invitación a cotizar.', on_delete=django.db.models.deletion.CASCADE, to='purchases_app.invitacioncotizar'),
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id_detalle_compra', models.AutoField(help_text='Identificador único del renglón de la orden de compra.', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(help_text='Unidades del producto solicitadas al proveedor.')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario según cotización vigente.', max_digits=10)),
                ('id_producto', models.ForeignKey(db_column='id_producto', help_text='Identificador único del producto.', on_delete=django.db.models.deletion.RESTRICT, to='catalog_app.producto')),
                ('id_orden', models.ForeignKey(db_column='id_orden', help_text='Identificador único de la orden de compra.', on_delete=django.db.models.deletion.CASCADE, to='purchases_app.ordencompra')),
            ],
            options={
                'db_table': 'detalle_orden_compra',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('cuit_prov', models.CharField(help_text='Identificador fiscal único del proveedor.', max_length=20, primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(help_text='Nombre comercial del proveedor.', max_length=255)),
                ('correo', models.CharField(blank=True, help_text='Correo electrónico de contacto del proveedor.', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto del proveedor.', max_length=50, null=True)),
                ('ofrece_envio', models.BooleanField(help_text='Indica si el proveedor realiza envíos.')),
                ('indice_confiabilidad', models.DecimalField(decimal_places=2, help_text='Indicador numérico de confiabilidad operacional del proveedor.', max_digits=10)),
                ('tiempo_promedio_entrega', models.IntegerField(help_text='Tiempo promedio de entrega en días.')),
                ('nivel', models.CharField(help_text='Clasificación del proveedor según su tipo comercial.', max_length=50)),
                ('id_direccion', models.ForeignKey(blank=True, db_column='id_direccion', help_text='Identificador único de la dirección.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo_app.direccion')),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='cuit_prov',
            field=models.ForeignKey(db_column='cuit_prov', help_text='Identificador fiscal único del proveedor.', on_delete=django.db.models.deletion.RESTRICT, to='purchases_app.proveedor'),
        ),
        migrations.AddField(
            model_name='invitacioncotizar',
            name='cuit_prov',
            field=models.ForeignKey(db_column='cuit_prov', help_text='Identificador fiscal único del proveedor.', on_delete=django.db.models.deletion.CASCADE, to='purchases_app.proveedor'),
        ),
        migrations.CreateModel(
            name='RegistroCompra',
            fields=[
                ('id_compra', models.AutoField(help_text='Identificador único del registro de compra o gasto.', primary_key=True, serialize=False)),
                ('origen_vendedor', models.CharField(help_text='Origen o proveedor del gasto pagado.', max_length=255)),
                ('descripcion_articulo', models.CharField(help_text='Detalle del artículo o servicio adquirido.', max_length=1000)),
                ('motivo', models.CharField(help_text='Justificación operativa del gasto.', max_length=500)),
                ('monto_pagado', models.DecimalField(decimal_places=2, help_text='Monto abonado en la transacción.', max_digits=10)),
                ('fecha_compra', models.TimeField(help_text='Fecha y hora exacta de la operación.')),
                ('impacto_stock', models.BooleanField(help_text='Indica si la compra ingresó como artículo al inventario.')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', help_text='Identificador único del producto.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog_app.producto')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', help_text='Identificador único del usuario.', on_delete=django.db.models.deletion.RESTRICT, to='users_app.usuario')),
            ],
            options={
                'db_table': 'registro_compra',
            },
        ),
        migrations.AddField(
            model_name='invitacioncotizar',
            name='id_solicitud',
            field=models.ForeignKey(db_column='id_solicitud', help_text='Identificador único de la solicitud de cotización.', on_delete=django.db.models.deletion.CASCADE, to='purchases_app.solicitudcotizacion'),
        ),
        migrations.CreateModel(
            name='SolicitudCotizacionProducto',
            fields=[
                ('id_solicitud_producto', models.AutoField(help_text='Identificador único del detalle de solicitud.', primary_key=True, serialize=False)),
                ('id_producto', models.ForeignKey(db_column='id_producto', help_text='Identificador del producto solicitado.', on_delete=django.db.models.deletion.RESTRICT, to='catalog_app.producto')),
                ('id_solicitud', models.ForeignKey(db_column='id_solicitud', help_text='Identificador de la solicitud de cotización.', on_delete=django.db.models.deletion.CASCADE, to='purchases_app.solicitudcotizacion')),
            ],
            options={
                'db_table': 'solicitud_cotizacion_producto',
            },
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='productos',
            field=models.ManyToManyField(help_text='Relación M:N entre solicitud de cotización y productos requeridos.', through='purchases_app.SolicitudCotizacionProducto', to='catalog_app.producto'),
        ),
    ]
