# Generated by Django 6.1.1 on 2026-09-28 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(help_text='Identificador único del usuario.', primary_key=True, serialize=False)),
                ('email', models.CharField(help_text='Correo electrónico utilizado como contacto y autenticación.', max_length=255, unique=True)),
                ('contrasena', models.CharField(help_text='Clave encriptada para autenticarse.', max_length=255)),
                ('fecha_registro', models.DateField(help_text='Fecha en que el usuario se registró en el sistema.')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id_rol', models.AutoField(help_text='Identificador único del rol.', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(help_text='Nombre legible del rol asignado a usuarios.', max_length=100)),
                ('descripcion', models.CharField(blank=True, help_text='Detalle de funciones y permisos asociados al rol.', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'rol_usuario',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', help_text='Identificador único del usuario.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users_app.usuario')),
                ('dni', models.CharField(blank=True, help_text='Documento para facturación tomado en la primera compra.', max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, help_text='Número telefónico principal del usuario.', max_length=50, null=True)),
                ('telefono_alt', models.CharField(blank=True, help_text='Número telefónico alternativo del usuario.', max_length=50, null=True)),
                ('foto_perfil', models.CharField(blank=True, help_text='URL a la imagen de perfil del usuario.', max_length=500, null=True)),
                ('nombre', models.CharField(blank=True, help_text='Nombre real del usuario.', max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, help_text='Apellido real del usuario.', max_length=100, null=True)),
            ],
            options={
                'db_table': 'perfil_usuario',
            },
        ),
        migrations.CreateModel(
            name='PreferenciasUsuario',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', help_text='Identificador único del usuario.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users_app.usuario')),
                ('noti_c', models.BooleanField(help_text='Preferencia para recibir notificaciones por correo electrónico.')),
                ('noti_w', models.BooleanField(help_text='Preferencia para recibir notificaciones por WhatsApp.')),
                ('modo_oscuro', models.BooleanField(help_text='Preferencia visual de tema oscuro.')),
            ],
            options={
                'db_table': 'preferencias_usuario',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', help_text='Identificador único del rol.', on_delete=django.db.models.deletion.RESTRICT, to='users_app.rolusuario'),
        ),
        migrations.CreateModel(
            name='TokenSeguridad',
            fields=[
                ('id_token', models.AutoField(help_text='Identificador único del token.', primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Código generado para validación.', max_length=50)),
                ('fecha_expiracion', models.TimeField(help_text='Fecha y hora de expiración del token.')),
                ('utilizado', models.BooleanField(help_text='Indica si el token ya fue canjeado.')),
                ('fecha_desbloq', models.TimeField(blank=True, help_text='Fecha y hora de desbloqueo por intentos.', null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', help_text='Identificador único del usuario.', on_delete=django.db.models.deletion.CASCADE, to='users_app.usuario')),
            ],
            options={
                'db_table': 'token_seguridad',
            },
        ),
    ]
